export const BRANCHES = [
  "OBA Banne",
  "OBA Bijlmer",
  "OBA Bos en Lommer",
  "OBA Buitenveldert",
  "OBA CC Amstel",
  "OBA De Hallen",
  "OBA Diemen",
  "OBA Duivendrecht",
  "OBA Geuzenveld",
  "OBA IJburg",
  "OBA Javaplein",
  "OBA Linnaeus",
  "OBA Mercatorplein",
  "OBA Molenwijk",
  "OBA Olympisch Kwartier",
  "OBA Osdorp",
  "OBA Ouderkerk",
  "OBA Postjesweg",
  "OBA punt Casa Sofia",
  "OBA punt Ganzenhoef",
  "OBA Reigersbos",
  "OBA Roelof Hartplein",
  "OBA Slotermeer",
  "OBA Spaarndammerbuurt",
  "OBA Staatsliedenbuurt",
  "OBA Van der Pek",
  "OBA Waterlandplein",
  "OBA Weesp"
];
